// models/Room.js
import mongoose from "mongoose";

const playerSchema = new mongoose.Schema({
  // MODIFIED: Use a persistent ID generated by the client to uniquely identify players.
  _id: { type: String, required: true },
  name: { type: String, required: true },
  country: { type: String, required: true },
  isHost: { type: Boolean, default: false },
});

const roomSchema = new mongoose.Schema(
  {
    roomCode: { type: String, required: true, unique: true },
    curriculum: { type: String, enum: ["Local", "Cambridge"], required: true },
    subject: { type: String, required: true },
    level: {
      type: String,
      enum: ["Very Easy","Easy (Foundation)","Intermediate","Advanced","Expert","Master"],
      required: true,
    },
    profilePic: { type: String },
    maxPlayers: { type: Number, required: true },
    hostName: { type: String, required: true },
    hostCountry: { type: String, required: true },
    players: [playerSchema],
    targetScore: { type: Number, default: 10 },
    // NEW: Explicitly store the host's unique ID for easy access.
    hostId: { type: String, required: true },
  },
  { timestamps: true }
);

export const Room = mongoose.model("Room", roomSchema);
export default Room;